# Generated by Django 5.0.2 on 2024-02-27 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_first_name_customer_given_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='given_name',
            new_name='first_name',
        ),
    ]
